spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/db
    username: postgres
    password: admin
    driverClassName: org.postgresql.Driver
  rabbitmq:
    password: guest
    username: guest





camunda.bpm.admin-user:
  id: admin
  password: admin



rabbitmqProperties:
  queue-name: sira1
  routing-name: route1
  exchange-name: amq.topic
